[package]
name = "apple-stock-chart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
time = { version = "0.3.34", features = ["macros"] }
tokio = { version = "1.36.0", features = ["full"] }
yahoo_finance_api = { git = "https://github.com/meuter/yahoo_finance_api" }
